jwt:
    secret: "secret"
spring:
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: "jdbc:mysql://localhost:3306/rates"
        username: "root"
        password: "root"
server:
    port: 8084
